### ISSUE TITLE
Update or remove values in README

### ISSUE THREAD

**Issue by lukemorton** [madetech/handbook#240]
Our values have been revised considerably since they were added to the Handbook. In fact they are completely different to the ones currently I'm the README.

They are:
- Client first
- Drive to deliver
- Learning
- Mentoring
- Pragmatism
- Above and beyond

However just updating them and listing them won't mean much to anyone who doesn't already have the context and can refer to examples of what they actually mean.

What can we do to update our values and make them meaningful in the Handbook? The last comradro held on values had a few people suggest they find them meaningless when they are added to the Handbook without context. I'd like to avoid this.

One option is to remove them completely too.

cc @yaseminercan

**Comment by davidwinter** [comment]
I think it's important to have them in the handbook. Why can't we just add a bit of context for each in the handbook so it's easy for people to understand them?

**Comment by kjdchapman** [comment]
+1 to having them in the handbook.

These would be useful for me with enough context. I'd suggest adding context with two key angles:
- weighing them up against things we value less
- telling stories about applying them

So for example:

**Drive to deliver**
We value meeting delivery commitments over seeking the 'perfect' solution. 

That means when building a feature, we'll accept that it might not be the best version, and focus on getting it done and into production before iterating.
____________________

As a separate discussion, I am not sure these are our values / this is the right list.

(I'm not sure if an RFC is the right forum for either discussion.)

**Comment by danielburnley** [comment]
I think context would be good - I have issues with these values that I think could be discussed in a better forum, but the primary one is that just reading these in a vacuum would make me think "Yikes this is a company where they want me to overwork and have a bad work life balance" (in particular "Client first", "Drive to deliver", and "Above and beyond"). 

I think if we're going to put the values into the handbook we need to ensure they do fully reflect what our values are as a company - as well as provides some good concrete examples which removes the fear of "Oh Above and beyond, that means they want us to work 12hour days". Whereas as a person who has worked here long enough I know our values are more nuanced than that.

(This comes from the mind set of someone who is very vigilant of their work-life balance and so might be a bit more of an exaggerated reaction to reading these than most. I'm also not 100% sure that this is the right place to air this concern so am willing to move this comment elsewhere if it's more appropriate there)

**Comment by yaseminercan** [comment]
Very good points. Without us adding context, people will add their own and that could be misleading.

We should probably have one awesome example per value at least to add before adding them in a public forum.

I would love to hear concerns about those values actually. Maybe we could run another comradro now that we’ve had some time to understand those values better?

**Comment by lukemorton** [comment]
Latest updates address this issue: #338 and #339.
