### ISSUE TITLE
The "Learning (Engineering)" section suggests that "Learn Tech" is an Engineering only affair

### ISSUE THREAD

**Issue by adrianclay** [madetech/handbook#318]
> All Permanent Engineers are expected to attend and be on time.

**Comment by mattbee** [comment]
There's a PR for this and much more around new Learn Tech open here: https://github.com/madetech/handbook/pull/328

**Comment by lukemorton** [comment]
@mattbee Did your changes in #328 close this issue?

**Comment by mattbee** [comment]
Ah yes, I meant to close this (then it slipped my mind).
Thanks for the nudge.
