### ISSUE TITLE
Employee Assistance mentions credentials that no longer exist

### ISSUE THREAD

**Issue by LewisDaleUK** [madetech/handbook#336]
https://github.com/madetech/handbook/blob/master/guides/welfare/employee_assistance.md

> Online: You can visit http://employeeassistance.org.uk to access help via the website. You'll find the password for access in LastPass.

We no longer use LastPass and the credentials aren't stored in our current password manager

**Comment by lukemorton** [comment]
This has now been added to our current password management.

**Comment by lukemorton** [comment]
Fixed by #341. Thanks @LewisDaleUK!
