### ISSUE TITLE
Cycle to Work Scheme

### ISSUE THREAD

**Issue by ccp92** [madetech/handbook#411]
We currently list Mango Bikes under our cycle to work scheme. (https://www.mangobikes.com/help/#cycle-schemes)

This is now a dead link, and under their own help page they no longer offer that as a payment method: https://mangobikes.com/help/#biketowork

> Our DNA is to keep everything simple.
> Always has been, always will be. That’s Mango Bikes.
> From designing and sourcing parts, to building and selling our bikes; we hate middlemen and love keeping it simple.
> But we let that slip, and there were too many cooks spoiling the Mango broth.
> Bike to Work had got a bit too Don Corleone, so we no longer offer it as a payment method.
> We’ve got other dazzlingly good payment methods. Make sure you check them out if you want to finance your Mango.

**Comment by yaseminercan** [comment]
We should remove that link. I know a couple of people have bought a bike in the past year. We could update the link with another one or just remove it

**Comment by ccp92** [comment]
Resolved in https://github.com/madetech/handbook/pull/412 (thanks @StevenLeighton21)
