### ISSUE TITLE
Engineering roles still have old names in SFIA docs

### ISSUE THREAD

**Issue by Joseaie** [madetech/handbook#678]
I noticed that the titles on some of the engineering roles still had their old names (e.g Associate Software Engineer -> Software Engineer 1) in the SFIA folder. Is this something that needs updating?

**Comment by reub-the-cube** [comment]
Yes, I think it is - good spot! Would you like to open a PR for it @Joseaie?

**Comment by Joseaie** [comment]
Yeah, sure! :)
Would I need to change the file names as well or just the title on the files?

**Comment by reub-the-cube** [comment]
Yes please! File names / references - anything that makes it clearer would be great! I'll keep an eye out for PR 👀 🙏

**Comment by Joseaie** [comment]
PR is up! @reub-the-cube 😊

**Comment by reub-the-cube** [comment]
Excellent! [You'll get notifications but] I added a x-ref with the PR and approved along with someone else.

**Comment by Joseaie** [comment]
Thank you! 😊
