### ISSUE TITLE
Diversity and Inclusion

### ISSUE THREAD

**Issue by lukemorton** [madetech/handbook#70]
I think we need to improve our language in our values to incorporate diversity and inclusion.

I've raised this as an issue over in our BizOps repo: https://github.com/madetech/bizops/pull/168

**Comment by sowasred2012** [comment]
Personally I think these are both covered in:

> We value a positive and diverse company culture, and will always strive to adapt our culture in order to make this a more welcoming place to be

and 

> We value and respect the people we work with

**Comment by lukemorton** [comment]
There are a couple of areas I think needs work:

- We don't talk about how we are adapting our hiring processes to be more diverse
- We don't talk about "inclusion" as a concept anywhere

**Comment by lukemorton** [comment]
I think our values are quite good at covering diversity and inclusion even though the latter is more implicit rather than explicit.

GitLab go to extreme lengths in their handbook: https://about.gitlab.com/handbook/values/

Unsure I'd go into as much detail but I love the fact they pull out their thoughts on Diversity.

**Comment by sowasred2012** [comment]
- but surely valuing a diverse culture infers those things?
- and yeah, I'd agree it's implicit rather than explicit, but I'd go so far as to say it's kind of _explicitly_ implicit in that the only thing we're not doing is using the word `inclusion`.
- GitLab's values are wayyyyyyy long ;) part of the mission with writing these values was to condense them down.

**Comment by lukemorton** [comment]
Yeah really like what you and Ryan did with the values. I'm not really talking about changing them. (Apart from maybe adding the word inclusion but not a big deal.) 

Think we need to pull diversity and inclusion into a separate page in handbook perhaps to identify it as a problem of ours and that we're committed to tackling it. Also need to include things in hiring process around anonymous filtering on hired.com and working with diversity focussed recruiters.

Looking for help and thoughts on these really.

**Comment by chrisblackburn** [comment]
Are values the place to talk about hiring practices?

**Comment by lukemorton** [comment]
@chrisblackburn Nope, I'm specifically talking about here: https://github.com/madetech/handbook/tree/master/guides/hiring

**Comment by sowasred2012** [comment]
Oh OK - sorry, misunderstood :)

**Comment by lukemorton** [comment]
Closing as need to reframe/be more specific about the issue.
