### ISSUE TITLE
Supporting the health of our team

### ISSUE THREAD

**Issue by lukemorton** [madetech/handbook#71]
Currently we're [quite flexible](https://github.com/madetech/handbook/blob/master/guides/policies/sick_leave.md) when dealing with illness like colds and flu in the business. Our flexible work hours and untracked holiday make taking time off for illness less of an issue.

We don't however make explicit that it's okay for the team to take time off due to stress, bereavement and other mental health issues. We also do not provide frameworks for employees to seek help in these areas even though the pressure of delivery can sometimes impact mental health.

I'd like to start investigating what we can do to tackle this head on.

I believe @davidwinter has talked about Mind charity, and I've been told about employee wellness programmes like http://www.wsm-wellbeing.co.uk/.

Love to collect thoughts from the wider team.

**Comment by naliwajek** [comment]
Awesome idea 👍 👍 👍

**Comment by naliwajek** [comment]
> Love to collect thoughts from the wider team.

I had some serious issues with my eye sight previously due to stress and too much hours spent in front of a screen without taking appropriate breaks. So, I'm strongly in favour of providing a healthy work-style for everyone.

**Comment by naliwajek** [comment]
Plus working environment is important as well but that's already in progress so no ranting here.

**Comment by RyanMacG** [comment]
It's probably worth highlighting local health trusts for those of us in London https://www.myhealth.london.nhs.uk/mental-health-trusts

**Comment by RoryMacDonald** [comment]
Top work in highlighting this @lukemorton and @davidwinter.

I'd really like to see us offering more support around mental health. If (and more likely when) people need this, it should be easily available to them. It will impact **everyone** at some point. We can't ignore it. 

Another thing maybe worth touching on is issues in people's personal lives. Personal issues unquestionably impact work (and visa versa!), so if somebody is facing challenges in their personal life, then I think we have a responsibility to try and support them through this. I think it would be short-sighted of us to think people can 'leave their personal problems at home'. 

Where I'm less clear is how we draw the line between personal / professional and how much we can actually do to help. Would be interested to hear thoughts on this. 

One of the challenges I see is that most people are just not comfortable talking about mental health issues in a work environment. It's a *really* hard thing to do and I tend to find people talk about it when it reaches a crisis point. Is this just human nature or something better practices would improve? 

Few things that we could consider:

- Do we need to work on safety? 
- Can we give access to people like WSM anonymously? 
- Would it be valuable to have external HR? 
- Do we need to make it clearer who people need to speak to?
- How much of this comes from directors? 
- Does this tie into a lack of vulnerability? 
- How do we make sure that we're being consistent in any approach we take ?

**Comment by davidwinter** [comment]
Some quick links to the Mind website that have some really good information:

For employees: https://www.mind.org.uk/workplace/mental-health-at-work/taking-care-of-yourself/

For employers:

[How to support staff who are experiencing a mental health problem](https://www.mind.org.uk/media/550657/resource4.pdf)

[How to promote wellbeing and tackle the causes of work-related mental health problems](https://www.mind.org.uk/media/428496/Resource3_HowToPromoteWellBeingFINAL.pdf)

Basically, all of the PDFs on [this page](https://www.mind.org.uk/workplace/mental-health-at-work/taking-care-of-your-staff/useful-resources/) are super helpful and well worth a read. I read through a few of these a couple of weeks ago and will try and scan through and pick out the bits I found interesting to bring to this discussion.

**Comment by lukemorton** [comment]
#75 is just the start of what we need to do to support our team but I think it's a good start and something for us to be proud of.

Next steps:

- Run a session talking about recent changes (perhaps include in comradro)
- We should link to resources that David and Ryan have shared

**Comment by lukemorton** [comment]
I think #75 means we can close this issue for now but of course we're always looking to improve.
