### ISSUE TITLE
Email signatures

### ISSUE THREAD

**Issue by lukemorton** [madetech/handbook#8]
Are they even a thing anymore? If they are, should we standardise them?

**Comment by davidwinter** [comment]
Probably should be? Just for the cases where you might have forgotten to tell someone (outside of Made) that you're away on leave. 

I used this last time:

```
Thank you for you email.

I am currently on leave and will be back in the office on <DATE>.

If the matter is urgent please contact John Smith ( john@madetech.co.uk ), otherwise I will get back to you upon my return.

regards

David
```

**Comment by lukemorton** [comment]
"Thank you for you email." lol

**Comment by lukemorton** [comment]
Also that's not a signature.

**Comment by davidwinter** [comment]
2x #fail

**Comment by davidwinter** [comment]
Sorry, thought you was talking about #7

**Comment by RoryMacDonald** [comment]
Marketing mode:

* Think we should include our latest blog posts in our email signature? 
* I like the idea of include peoples faces in their signature. Don't know if that is a bit weird / an americanism?
* Switch to the Made Tech logo

**Comment by lukemorton** [comment]
Few things:
 - I've never had a signature whilst working at Made
 - I like clicking links in footers, particularly Twitter and blog posts
 - I think logos can look messy
 - Could we have a minimal, favicon style logo next to our name?
 - What about roles?
 - Signature shouldn't take away from the content of the email

**Comment by lukemorton** [comment]
@RoryMacDonald / @davidwinter any comments?

**Comment by RoryMacDonald** [comment]
* Everyone should have a signature.
* Would be good if we could use them for marketing. Share a snippet for QuizzBuzz / Book Launch et.c 
* I like clicking signatures / footer stuff too. Blog post / tweets +1
* Agree logos can look messy. Though think its useful from a branding point of view, particularly when you're emailing randoms, on big CC chains (like I get a lot with Akzo emails)
* Think roles are good thing to have in signature
* Think office number / mobile number
* Think link to website might be good too
* Think some sort of 'slogan' - helping companies to deliver software better could be neat too. Always pushing that company mission etc.

**Comment by RoryMacDonald** [comment]
Would quite like to sign everything with a physical signature

**Comment by RoryMacDonald** [comment]
https://www.dropbox.com/s/v7rh2sqshls79ta/Screenshot%202016-08-09%2022.33.29.png?dl=0

**Comment by RoryMacDonald** [comment]
http://www.wisestamp.com/corporate/

^^ $?

**Comment by davidwinter** [comment]
Maintaining signatures with new content and stuff to make sure things don't get outdated might become a pain/chore. That wisestamp thing looks like it could help us out with that.

Not too keen on actual handwritten signatures. Feels a bit gimmicky to me? (Sorry Rory!)

I think consistency is key. Nothing drives me more nuts than when fonts, colours and sizes are different between people in the same organisation. Well, there are other things that drive me more nuts, but in the context of email signatures.

**Comment by lukemorton** [comment]
Not a huge fan of the physical signature, but I like the idea of something like wisestamp to centrally manage things like this.

I'd prefer a most minimal solution possible to start with, we could always add more later.

Perhaps we could create 3-4 versions and get people to vote for their favourite?

**Comment by lukemorton** [comment]
+1 on the font thing, I'd even go as far as to say all of the content of the signature should not be in any particular font. Just the default client font. Of course a logo image would be the exception.

**Comment by davidwinter** [comment]
Less lines the better too.

**Comment by SebAshton** [comment]
Starters for 10 - http://jsfiddle.net/SebAshton/LctywpLa/embedded/result/dark

**Comment by davidwinter** [comment]
Even though above I said less lines, I prefer #7

**Comment by lukemorton** [comment]
Added a lightweight one in #8: http://jsfiddle.net/254v94ry/1/embedded/result/

**Comment by madetech-com** [comment]
Just added a signature to all accounts. Am using a thing called 'signaturesatori' @lukemorton @SebAshton @sowasred2012 @davidwinter you should have admin access to this and we can update these whenever we want.

@sowasred2012 @lukemorton might be worth adding a link to latest blog post when we release them, or when we launch the book etc.

**Comment by RoryMacDonald** [comment]
I've noticed some people @craigjbass @lukemorton are using smaller signatures. If we're going to change them, can we push to the rest of the team via signaturesatori ?
